package executor

import (
	"os/exec"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/kindship-ai/kindship-cli/internal/api"
)

func TestIsSessionConflictError(t *testing.T) {
	tests := []struct {
		name   string
		stderr string
		want   bool
	}{
		{"empty", "", false},
		{"canonical", "Session ID already in use", true},
		{"lowercase", "session id already in use", true},
		{"dashed-separator", "session-id already in-use", true},
		{"underscored", "session_id already_in_use", true},
		{"with comma", "session id, already, in use", true},
		{"with colon", "session id: already in use", true},
		{"embedded in longer message", "Error: Session ID already in use. Retry later.", true},
		{"with surrounding stack trace", "    at whatever\nSession ID already in use\n    at line 2", true},
		{"unrelated-error", "Could not find session", false},
		{"partial-match-fails", "session id in use", false},
		{"claude-stream-ok", "{\"type\":\"text\",\"text\":\"hello\"}", false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := isSessionConflictError(tc.stderr)
			if got != tc.want {
				t.Errorf("isSessionConflictError(%q) = %v, want %v", tc.stderr, got, tc.want)
			}
		})
	}
}

// newNoopSender returns a LogSender that discards log lines. Used by
// retry-loop tests so we don't need a fake API client.
func newNoopSender() LogSender {
	return func(lines []api.LogLine) error { return nil }
}

// newCapturingSender returns a LogSender that appends every line received
// to the returned slice pointer (protected by the caller via sync package
// if tests go parallel). Used to assert [kindship:session-conflict-retry]
// markers flow through the same path that reaches run logs in production.
func newCapturingSender() (LogSender, *[]api.LogLine) {
	var lines []api.LogLine
	sender := func(batch []api.LogLine) error {
		lines = append(lines, batch...)
		return nil
	}
	return sender, &lines
}

// countRetryMarkerLines counts how many captured log lines contain the
// canonical retry prefix. Used to assert one marker per retry attempt.
func countRetryMarkerLines(lines []api.LogLine) int {
	count := 0
	for _, l := range lines {
		if strings.Contains(l.Content, sessionConflictLogPrefix) {
			count++
		}
	}
	return count
}

// withFakeCommand swaps commandContext for the duration of a test and
// returns a restore function. The fake command is generated by `maker`
// which is called with the attempt index (1-based) so each attempt can
// produce different output.
func withFakeCommand(t *testing.T, maker func(attempt int) *exec.Cmd) func() {
	t.Helper()
	original := commandContext
	attemptRef := &atomic.Int64{}
	commandContext = func(name string, args ...string) *exec.Cmd {
		attempt := int(attemptRef.Add(1))
		return maker(attempt)
	}
	return func() { commandContext = original }
}

// fakeCmd builds an *exec.Cmd that, when Run, writes `stdout` to stdout,
// `stderr` to stderr, and exits with `exitCode`. Using /bin/sh via
// printf keeps behavior portable across Linux + macOS dev boxes.
func fakeCmd(stdout, stderr string, exitCode int) *exec.Cmd {
	script := ""
	if stdout != "" {
		script += "printf '%s' " + shellQuote(stdout) + "; "
	}
	if stderr != "" {
		script += "printf '%s' " + shellQuote(stderr) + " 1>&2; "
	}
	script += "exit " + itoa(exitCode)
	return exec.Command("/bin/sh", "-c", script)
}

func shellQuote(s string) string {
	// Simplest safe quoting: replace ' with '\'' then wrap in single quotes.
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	out := ""
	for n > 0 {
		out = string(rune('0'+n%10)) + out
		n /= 10
	}
	if neg {
		out = "-" + out
	}
	return out
}

// Retry-loop behavior: conflict on attempt 1 → retry → success on attempt 2.
// Asserts the plan's full checklist at this layer: invocation count,
// ExecutionResult-equivalent exit code, AND the [kindship:session-conflict-retry]
// marker flowed through the LogSender path once (one retry = one marker).
func TestRunClaudeWithRetry_OneRetryThenSuccess(t *testing.T) {
	attempts := &atomic.Int64{}
	restore := withFakeCommand(t, func(attempt int) *exec.Cmd {
		attempts.Add(1)
		if attempt == 1 {
			return fakeCmd("", "Session ID already in use", 1)
		}
		return fakeCmd("success body", "", 0)
	})
	defer restore()

	sender, capturedRef := newCapturingSender()
	seq := &atomic.Int64{}
	start := time.Now()
	_, stderrBuf, exitCode, execErr := runClaudeWithRetry(
		"claude", "claude", []string{}, sender, seq, true,
	)
	elapsed := time.Since(start)

	if exitCode != 0 {
		t.Errorf("expected success exitCode 0, got %d (execErr=%v)", exitCode, execErr)
	}
	if got := int(attempts.Load()); got != 2 {
		t.Errorf("expected 2 invocations (one retry then success), got %d", got)
	}
	if strings.Contains(stderrBuf.String(), "Session ID already in use") {
		t.Errorf("final stderr unexpectedly contains attempt-1 error: %q", stderrBuf.String())
	}
	if markers := countRetryMarkerLines(*capturedRef); markers != 1 {
		t.Errorf("expected exactly 1 [kindship:session-conflict-retry] marker, got %d", markers)
	}
	if elapsed < 2*time.Second {
		t.Errorf("expected elapsed >= 2s (one retry sleep), got %v", elapsed)
	}
	if elapsed > 4*time.Second {
		t.Errorf("expected elapsed < 4s (one retry sleep), got %v", elapsed)
	}
}

// Retry-loop behavior: all three attempts fail with conflict → exhausted.
// Timing window: 2× sleeps, each 2000-2999ms → elapsed in [4s, 6s].
func TestRunClaudeWithRetry_ExhaustsRetries(t *testing.T) {
	attempts := &atomic.Int64{}
	restore := withFakeCommand(t, func(attempt int) *exec.Cmd {
		attempts.Add(1)
		return fakeCmd("", "Session ID already in use", 1)
	})
	defer restore()

	sender, capturedRef := newCapturingSender()
	seq := &atomic.Int64{}
	start := time.Now()
	_, stderrBuf, exitCode, _ := runClaudeWithRetry(
		"claude", "claude", []string{}, sender, seq, true,
	)
	elapsed := time.Since(start)

	if exitCode == 0 {
		t.Errorf("expected non-zero exitCode on exhaustion, got %d", exitCode)
	}
	if got := int(attempts.Load()); got != sessionConflictMaxAttempts {
		t.Errorf("expected %d invocations, got %d", sessionConflictMaxAttempts, got)
	}
	// Two retry attempts between the 3 invocations → 2 markers.
	if markers := countRetryMarkerLines(*capturedRef); markers != 2 {
		t.Errorf("expected 2 [kindship:session-conflict-retry] markers, got %d", markers)
	}
	// Must fall inside [2*base, 2*(base+jitterMax)) → [4000ms, 6000ms).
	// Allow 500ms of slack for fake-command startup overhead on dev laptops;
	// CI is usually tighter but the slack prevents flaky tests.
	minMs := 2 * sessionConflictBaseDelayMs
	maxMs := 2*(sessionConflictBaseDelayMs+sessionConflictJitterMaxMs) + 500
	if elapsed < time.Duration(minMs)*time.Millisecond {
		t.Errorf("expected elapsed >= %dms, got %v", minMs, elapsed)
	}
	if elapsed > time.Duration(maxMs)*time.Millisecond {
		t.Errorf("expected elapsed <= %dms, got %v", maxMs, elapsed)
	}
	// The FINAL stderr should still contain the conflict marker (attempt 3's stderr).
	if !strings.Contains(stderrBuf.String(), "Session ID already in use") {
		t.Errorf("final stderr missing conflict marker: %q", stderrBuf.String())
	}
}

// Retry-loop behavior: flag disabled → single attempt, no retry even on conflict.
func TestRunClaudeWithRetry_FlagDisabledNoRetry(t *testing.T) {
	attempts := &atomic.Int64{}
	restore := withFakeCommand(t, func(attempt int) *exec.Cmd {
		attempts.Add(1)
		return fakeCmd("", "Session ID already in use", 1)
	})
	defer restore()

	seq := &atomic.Int64{}
	_, _, exitCode, _ := runClaudeWithRetry(
		"claude", "claude", []string{}, newNoopSender(), seq, false, // flag=false
	)

	if exitCode == 0 {
		t.Errorf("expected non-zero exitCode (no retry), got %d", exitCode)
	}
	if got := int(attempts.Load()); got != 1 {
		t.Errorf("expected 1 invocation (no retry), got %d", got)
	}
}

// Retry-loop behavior: non-Claude CLI never retries, even with flag enabled.
func TestRunClaudeWithRetry_NonClaudeNoRetry(t *testing.T) {
	attempts := &atomic.Int64{}
	restore := withFakeCommand(t, func(attempt int) *exec.Cmd {
		attempts.Add(1)
		return fakeCmd("", "Session ID already in use", 1)
	})
	defer restore()

	seq := &atomic.Int64{}
	_, _, exitCode, _ := runClaudeWithRetry(
		"codex", "codex", []string{}, newNoopSender(), seq, true, // flag=true but cli=codex
	)

	if exitCode == 0 {
		t.Errorf("expected non-zero exitCode (codex doesn't retry), got %d", exitCode)
	}
	if got := int(attempts.Load()); got != 1 {
		t.Errorf("expected 1 invocation for non-Claude cli, got %d", got)
	}
}
